name: copernicus-solar
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - nbformat
  - nbclient
  - shap
  - opencv
  - pip
